language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
before_script: npm run bootstrap
script:
  - 'npm run test:coverage'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  # Make a release
  - npx lerna version --yes --github-release
  - npx lerna publish from-git --yes
